services:
    backend:
        build:
            context: .
            dockerfile: Flask/Dockerfile
        volumes:
            - ./Flask/src:/volume
            - ./Flask/src/uploaded_file:/uploaded_file
        ports:
            - 8001:8001

    # middleware:
    #     build:
    #         context: .
    #         dockerfile: ./middleware/Dockerfile
    #     volumes:
    #         - ./middleware:/volume
    #     ports:
    #         - 8000:8000

    frontend:
        build:
            context: .
            dockerfile: ./frontend/Dockerfile 
        volumes:
            - ./frontend:/volume
        ports:
            - 3000:3000
        # depends_on:
        #     - "middleware"