services:
    backend:
        build:
            context: ./Flask/
        # volumes:
        #     - ./Flask/src:/src
        ports:
            - 8001:8001

    middleware:
        build:
            context: ./middleware
        # volumes:
        #     - .:/app
        ports:
            - 8000:8000

    frontend:
        build:
            context: ./frontend/ # path to Dockerfile for frontend
        # volumes:
        #     - ./frontend/src:/app/src
        ports:
            - 3000:3000
        depends_on:
            - "backend"