services:
    db:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: securepwd
            POSTGRES_USER: postgres
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql



    adminer:
        image: adminer
        restart: always
        ports:
            - 1234:8080
        depends_on:
            - "db"

    memcached:
        image: 'memcached'
        ports:
            - '11211:11211'
        restart: always
        
    app:

        build:
            context: ../
            dockerfile: ./Flask/Dockerfile
        ports:
            - 5000:5000
        depends_on:
            - "db"
            - memcached
